-------------------------------------------------------------------------------
Test set: in.meenasubramanian.kaithari.TestCreateTask
-------------------------------------------------------------------------------
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.082 s <<< FAILURE! - in in.meenasubramanian.kaithari.TestCreateTask
in.meenasubramanian.kaithari.TestCreateTask.testCreateTaskWithValidData()  Time elapsed: 0.022 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception thrown: in.meenasubramanian.kaithari.exception.ValidationException: Due Date can not be in the Past
	at org.junit.jupiter.api.AssertDoesNotThrow.createAssertionFailedError(AssertDoesNotThrow.java:83)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:54)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:37)
	at org.junit.jupiter.api.Assertions.assertDoesNotThrow(Assertions.java:3135)
	at in.meenasubramanian.kaithari.TestCreateTask.testCreateTaskWithValidData(TestCreateTask.java:34)
Caused by: in.meenasubramanian.kaithari.exception.ValidationException: Due Date can not be in the Past
	at in.meenasubramanian.kaithari.util.StringUtil.rejectIfInvalidDate(StringUtil.java:17)
	at in.meenasubramanian.kaithari.validation.TaskValidator.validate(TaskValidator.java:15)
	at in.meenasubramanian.kaithari.serviece.TaskServiece.create(TaskServiece.java:29)
	at in.meenasubramanian.kaithari.TestCreateTask.lambda$0(TestCreateTask.java:35)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:50)
	... 16 more

